tarefaconcurso        =   [{"materia":"Língua Portugues","time":0},{"materia":"Racocínio Lógico","time":0},{"materia":"Informática","time":0},{"materia":"Administração","time":0},{"mateira":"Noções de contabilidade","time":0},{"materia":"Direito Constitucional","time":0},{"materia":"Direito Penal","time":0},{"materia":"Processual penal","time":0},{"materia":"Direito Admnistrativo","time":0},{"materia":"Medicina Legal","time":0}]
tarefaescola          =   [{"materia":"materiasdaescola","time":0}]
tarefaprojetos        =   [{"materia":"Mydict","time":0},{"materia":"siteMYdict","time":0},{"materia":"Calendario-Agenda","time":0}]
tarefalivros          =   [{"livro":"informatica","time":0}]
tarefas               =   [tarefaconcurso,tarefaescola,tarefaprojetos,tarefalivros]